<?php


namespace Phespro\Phespro\Tests;


use Laminas\Diactoros\ServerRequestFactory;
use League\Route\Router;
use Phespro\Phespro\Configuration\FrameworkConfiguration;
use Phespro\Phespro\Extensibility\AbstractExtension;
use Phespro\Phespro\Kernel;
use PHPUnit\Framework\TestCase;

class ErrorHandlerTestPlugin extends AbstractExtension
{
    function boot(Kernel $kernel): void
    {
        parent::boot($kernel); // TODO: Change the autogenerated stub
    }

    function bootHttp(Router $router): void
    {
        $router->get('/', function() {
            throw new \Exception('Testexception');
        });
    }
}

class ErrorHandlingTest extends TestCase
{
    /**
     * @throws \Phespro\Container\ServiceNotFoundException
     * @covers \Phespro\Phespro\ErrorHandlerMiddleware
     */
    public function test()
    {
        $kernel = new Kernel([
            ErrorHandlerTestPlugin::class,
        ]);
        $kernel->decorate('config', fn($container, $prev) => new FrameworkConfiguration(
            displayErrorDetails: true,
        ));
        $response = $kernel->handleWebRequest(false, (new ServerRequestFactory)->createServerRequest('GET', '/'));
        $this->assertEquals(500, $response->getStatusCode());
    }
}