#!/usr/bin/env php
<?php

use Laminas\Diactoros\Response;
use League\Route\Router;
use Phespro\Phespro\Extensibility\AbstractExtension;
use Phespro\Phespro\Kernel;
use Phespro\ReactPHPServer\ReactExtension;

require __DIR__ . '/../../../vendor/autoload.php';

class MyExtension extends AbstractExtension
{
    function bootHttp(Kernel $kernel, Router $router): void
    {
        $router->get('/', function () {
            $response = new Response();
            $response->getBody()->write('test');
            return $response;
        });
    }
}

$kernel = new Kernel([
    ReactExtension::class,
    MyExtension::class,
]);

$kernel->handleCli();
